language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer config --global github-protocols 'https'
    - composer update --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-text
